include(${CMAKE_CURRENT_LIST_DIR}/../base.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/../zlib/load.cmake)
SetEnvVariables(${ZLIB_INSTALL_DIR})
#MakeReadyNow(PATH ${CMAKE_CURRENT_LIST_DIR} VERSION t0.0.7)
MakeReadyNow(PATH ${CMAKE_CURRENT_LIST_DIR} VERSION 1.5.0)
